repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.4
    hooks:
      - id: terraform_fmt
      - id: terraform_trivy
      - id: terraform_validate
        exclude: '(.*\/modules)'
        args:
          - --args=-json
          - --args=-no-color
